### ISSUE TITLE
CreateAction with Backslash

### ISSUE THREAD

**Issue by Scuzz3y** [KCarretto/arsenal-api-python-client#2]
Client error when creating an action with a backslash in the string to reference a path for Windows.

**Comment by KCarretto** [comment]
This should be fixed. The following are now acceptable:

`CreateAction <Target> exec dir C:\\\\System32`
`CreateAction <Target> exec dir 'C:\\System32'`

If the quotes are necessary, you may escape them like so:

`CreateAction <Target> exec dir \'C:\\\\System32\'`
